### ISSUE TITLE
Add glob support

### ISSUE THREAD

**Issue by rtivital** [shakacode/sass-resources-loader#10]
Currently I need to install [Glob](https://github.com/isaacs/node-glob) package separately to match all files in resources folder:
```js
// webpack config
const glob = require('glob');
module.exports = {
  // ...
  sassResources: glob.sync('./src/styles/resources/**/*.scss'),
};
``` 

It would be really great if sass-resources-loader could recognize these patterns out of the box, e.g.
```js
module.exports = {
  // ...
  sassResources: './src/styles/resources/**/*.scss',
};
```

**Comment by justin808** [comment]
@rtivital Any chance that you want to hack on the loader and put in a PR?

Sounds like a great idea.

CC: @alexfedoseev

**Comment by rtivital** [comment]
@justin808 Well, I guess I've done it in https://github.com/shakacode/sass-resources-loader/pull/11

I've done some testing with provided example, everything seems just fine.

**Comment by justin808** [comment]
See #11.
