### ISSUE TITLE
Support @use along with @import

### ISSUE THREAD

**Issue by lucpotage** [shakacode/sass-resources-loader#110]
I tried to use the loader with the latest sass version and unfortunately it does not seem to support `@use` and `@forward` rules.

This would be a nice addition.

**Comment by justin808** [comment]
@lucpotage any chance that you can make a PR?

**Comment by lucpotage** [comment]
Here is more info about the [@use](https://sass-lang.com/documentation/at-rules/use) rule. Also, they [discourage](https://sass-lang.com/documentation/at-rules/import) the use of @import the moment your start using the latest version of Sass.

So, I suppose this loader would become a v3 since it's a breaking change. We should clearly inform developers about it.

I will try to create a PR.

**Comment by lucpotage** [comment]
I created a PR that I hope you will test. It needs extra work and I did not succeed in testing it properly. If you can, it would be great!

https://github.com/shakacode/sass-resources-loader/pull/111

**Comment by saltnpixels** [comment]
yes! I am looking for this as well

**Comment by justin808** [comment]
@saltnpixels if you could submit a PR, I'd surely get it reviewed!

**Comment by lucpotage** [comment]
Seeing this conversation https://github.com/webpack-contrib/sass-loader/issues/804, I suppose it's important to wait before starting anything with this loader.

In the meantime, I started to use postcss and realize I should have used it earlier. The ecosystem around the @use syntax is not mature. 😐

**Comment by justin808** [comment]
@lucpotage see https://github.com/webpack-contrib/sass-loader/issues/804#issuecomment-653057921

Can you confirm that we've got the `@use` feature fixed?

**Comment by justin808** [comment]
@saltnpixels, @lucpotage,  @Tomburgs 
 
# Released version 2.1.0 🎉.
