### ISSUE TITLE
The configuration of webpack4 in Vue has no effect

### ISSUE THREAD

**Issue by luoye111** [shakacode/sass-resources-loader#116]
![image](https://user-images.githubusercontent.com/34934450/79436005-eb0cdc80-8002-11ea-9198-1e6bf394c618.png)
![image](https://user-images.githubusercontent.com/34934450/79437786-3de79380-8005-11ea-9b1b-cba2c0b81dc1.png)

**Comment by justin808** [comment]
You'll have to do some research on this one. Feel free to request this to be reopened. @luoye111, maybe you already solved this?
