### ISSUE TITLE
Package is published with its development-only dependencies

### ISSUE THREAD

**Issue by thibaudcolas** [shakacode/sass-resources-loader#127]
The package shouldn’t be published with dependencies that are only used for development:

https://github.com/shakacode/sass-resources-loader/blob/ce2700db680bbe100a5f6b0b9edee5c740396dba/package.json#L37-L56

As far as I can see all of `@babel/cli`, `@babel/preset-env`, and `babel-eslint` are only used in development. They should be moved to `devDependencies`.

**Comment by justin808** [comment]
@thibaudcolas could you put this improvement and the one for #126 in a PR?

**Comment by justin808** [comment]
@Tomburgs, can you take this one?

**Comment by justin808** [comment]
Fixed a long time ago in #128.
