### ISSUE TITLE
How to change variables

### ISSUE THREAD

**Issue by EnVires** [shakacode/sass-resources-loader#131]
There are two themes in my project and I want to switch between them.
Themes are implemented as 2 scss styles with variables
![image](https://user-images.githubusercontent.com/15741748/99969727-8c32f100-2da3-11eb-84fd-c11781edd547.png)

how can i implement this?

**Comment by justin808** [comment]
I don't think your question is specific to this package.

I think you either will have to switch at build time, via some Webpack magic, or at runtime by using different variable names.
