### ISSUE TITLE
sass-resource-loader + Nativescript + Angular issue CONSOLE ERROR: Error: Css styling failed: Error: Invalid value for animation: 1ms

### ISSUE THREAD

**Issue by pandabuilt** [shakacode/sass-resources-loader#136]
When using sass-resource-loader I get the following errors.  

When defaulting styles within the projects and not using sass-resource-loader - it works (putting the code in dependencies inside a style sheet and use raw loader, resolve-url-loader and sass-loader.) However, when I add sass-resources-loader it fails with an error   

CONSOLE ERROR: Error: Css styling failed: Error: Invalid value for animation: 1ms
CONSOLE LOG: Angular is running in development mode. Call enableProdMode() to enable production mode.
CONSOLE ERROR: Error: Css styling failed: Error: Invalid value for animation: 1ms

And then the styles do not appear.
```
 {
              loader: 'sass-resources-loader',
              options: {
                sourceMap: true,
                resources: [
                    "dependencies.scss"
               ]
             }
}
```

**Comment by justin808** [comment]
See the example app:

https://github.com/shakacode/sass-resources-loader/blob/master/example/webpack.config.js#L42-L62

If you think there's still a problem in the library, please create a reproducible case and reopen this issue.

By the way, I have no idea if the this package works with NativeScript.
