### ISSUE TITLE
How to use sass-resources-loader with create-react-app (ejected)

### ISSUE THREAD

**Issue by jimmy-e** [shakacode/sass-resources-loader#137]
Please see [this repo](https://github.com/jimmy-e/cra-style-variables) for further information and reproduction.

I am using an ejected create-react-app and I want to be able to use global sass variables in an individual stylesheet without having to import the stylesheet. I think using `sass-resources-loader` is what I should use. I have updated the create-react-app ejected webpack config [here](https://github.com/jimmy-e/cra-style-variables/blob/master/config/webpack.config.js#L142-L147), but whenever I run `yarn start`, I still get the complaint:

>SassError: Undefined variable: "$boxSize".
        on line 5 of src/SampleComponent/sampleComponent.scss
>,   height: $boxSize;

Is there something that I am doing wrong in trying to use `sass-resources-loader` or should I be using something different instead? Thanks, and here are some file snippets below for more context:

**file structure:**
```
src/
  - SampleComponent/
    - SampleComponent.js
    - SampleComponent.scss
  - styles/
    - sizes.scss
  - index.js  
```

**SampleComponent.js:**
```js
import * as styles from './sampleComponent.scss';

const SampleComponent = () => (
  <div className={styles.div}>
    <h3>hello world</h3>
  </div>
);

export default SampleComponent;
```

**sampleComponent.scss:**
```css
.div {
  align-items: center;
  background: pink;
  display: flex;
  height: $boxSize;
  justify-content: center;
  margin: 5rem;
  width: $boxSize;
}
```

**sizes.scss:**
```css
$boxSize: 30rem;
```

**Comment by justin808** [comment]
Hi @jimmy-e, what was the issue?
