### ISSUE TITLE
of no avail  （scss still needs to be introduced）

### ISSUE THREAD

**Issue by xiaoxiaotongzhi** [shakacode/sass-resources-loader#141]
`{
          test: /\.scss$/,
          include: path.resolve(__dirname, 'src/global-css/'),
          loaders: [
            isDevMode ? 'style-loader?sourceMap' : MiniCssExtractPlugin.loader,
            { loader: 'css-loader', options: { sourceMap: isDevMode } },
            postloader,
            { loader: 'sass-loader', options: { sourceMap: isDevMode } },
            {
              loader: 'sass-resources-loader',
              options: {
                  resources: path.resolve(__dirname, 'src/global-css/_handler.scss')
              }
            },
          ],
        },`

**Comment by justin808** [comment]
@xiaoxiaotongzhi I don't understand what your issue is. Please update and reopen the issue.
