### ISSUE TITLE
Configure sass-rescource-loaer after sassloader and hack my page styles

### ISSUE THREAD

**Issue by PachVerb** [shakacode/sass-resources-loader#152]
**before configuration：**
this my webpack config code:
```js
...
 {
              // .scss/sass文件处理
              test: sassRegex,
              exclude: sassModuleRegex,
              use: [
                "style-loader",
                {
                  loader: "css-loader",
                  options: {
                    importLoaders: 1, // 查询参数 importLoaders，用于配置「css-loader 作用于 @import 的资源之前」有多少个 loader
                  },
                },
             "postcss-loader",
               {
                  loader: "sass-resources-loader", // 配置scss全局模块注入
                  options: {
                    resources: [
                      // 配置全局注入文件
                      path.resolve(paths.appSrc, "style/varibale.scss"),
                    ],
                  },
                },
             "sass-loader", //
        ],
 },
 ...
```
**head tag:** 

![image](https://user-images.githubusercontent.com/43908467/159127878-5914773b-a895-4b73-bd6c-0e7e60400685.png)

> oops, what happen ? After changing the loading order of the loader, this result appears, my style does not take effect, and it is caused by not injecting global variables

**after configuration：**
```js
...
{
       test: sassRegex,
       exclude: sassModuleRegex,
       use: [
         "style-loader",
           {
              loader: "css-loader",
              options: {
                    importLoaders: 1, 
               },
           },
           "postcss-loader",
           "sass-loader", 
            {
                loader: "sass-resources-loader", // 配置scss全局模块注入
                options: {
                    resources: [
                      // 配置全局注入文件
                      path.resolve(paths.appSrc, "style/varibale.scss"),
                    ],
                },
            },
        ],
 }
...
```

**result:**

![image](https://user-images.githubusercontent.com/43908467/159127666-6ccba42a-3d52-4cf7-8743-072e809dda8f.png)

> The result is correct, and after adjusting the configuration order, the global variable is not injected into the header under each style tag, but the variable is valid, which is very strange. why global variables are not injected

**expect:**help me. At present, I know the solution is to exchange the order of sass-resouce-loader and sass-loder. But why does this happen?

**Comment by justin808** [comment]
Please open a [discussion](https://github.com/shakacode/sass-resources-loader/discussions).
