### ISSUE TITLE
Update examples for webpack v5?

### ISSUE THREAD

**Issue by nsunga** [shakacode/sass-resources-loader#195]
Hello maintainers!

Pretty much the title. The readme notes working examples for v4, but what about v5?

Is it v5 supported? Looks like there arent any peerDependencies in package.json to signal that either.

Please let me know and thanks!

**Comment by justin808** [comment]
Yes, this works with Webpack v5. Yes, we need to update the examples. Help wanted!

**Comment by nsunga** [comment]
awesome and thank u :)
