### ISSUE TITLE
Query string options

### ISSUE THREAD

**Issue by serheyShmyg** [shakacode/sass-resources-loader#20]
Hi, I have  a task, which require couple different options for 'sass-resources-loader'.
Is it possible to add query string options?

**Comment by justin808** [comment]
@serheyShmyg Please feel free to provide a well documented PR. We'd love to consider it.

**Comment by serheyShmyg** [comment]
I saw, pull request about webpack 2.0 and there is query option is present.
Do you plan merge it https://github.com/shakacode/sass-resources-loader/pull/16?

**Comment by alexfedoseev** [comment]
@serheyShmyg I'll release #16 in the next couple of minutes, closing this. Feel free to reopen if it's not solved by #16.
