### ISSUE TITLE
Context missing

### ISSUE THREAD

**Issue by jmandreslopez** [shakacode/sass-resources-loader#22]
Angular: 2.4.6
Webpack: 2.2.1
sass-resources-loader: 1.2.0

This is my webpack.config:

```
{
    test: /\.scss$/,
    use: [
        // 'style-loader',
        // 'css-loader',
        'raw-loader',
        'sass-loader',
        {
            loader: 'sass-resources-loader',
            options: {
                resources: [
                    'src/assets/sass/variables.scss',
                    'src/assets/sass/mixins.scss',
                ]
            },
        },
    ],
    include: [helpers.root('src', 'styles')]
},
```

and every time I tried to build I'm getting this error:

`[sass-resources-loader]:  `options.context` is missing. Using current working directory as a root instead`

If I comment the 'sass-resources-loader' section the system works fine.

What am I missing?

**Comment by alexfedoseev** [comment]
@jmandreslopez Is this an error or just warning?

Most likely your config doesn't have [`context`](https://webpack.js.org/configuration/entry-context/#context) defined, so `sass-resources-loader` uses `process.cwd()` to resolve paths to files with resources.

**Comment by jmandreslopez** [comment]
You're right, is a warning. My bad. 

How do I get rid of it? I don't have context defined on my config but even adding: 

`context: '.'`

I'm getting the same warning.

**Comment by jmandreslopez** [comment]
Found the solution:

```
new LoaderOptionsPlugin({
      debug: true,
      options: {
            context: helpers.root('.')
      }
}),
```

Thanks :)

**Comment by alexfedoseev** [comment]
@jmandreslopez Also try:

```
context: __dirname
```

The idea is to pass an absolute path to your `context` as webpack might ignore `'.'` as it's not a univocal location and it won't treat it as `__dirname` for you.

**Comment by aight8** [comment]
Why context must defined as global option?

The doc says:
```
NOTE: If webpackConfig.context is not defined, process.cwd() will be used to resolve files with resource.
```

Is this a difference in webpack 2 ?!

**Comment by alexfedoseev** [comment]
> Why must the context defined as global option?

It's not required. But w/o context I can't resolve relative paths, so using `process.cwd()` instead. If it doesn't work for you for some reason, just provide `context`.
