### ISSUE TITLE
Question about rules duplication

### ISSUE THREAD

**Issue by LeonardoGentile** [shakacode/sass-resources-loader#23]
Hello, thanks for this 👍 

I've been studying the migration from old (global) sass files to css modules (still using sass) with webpack and react.
As I've understond given the nature of css modules, wether by using this loader or not, we need to import the common sass files (vars, mixins, extr) into each of the sass file requiring them.

At this point something is not clear, wouldn't this duplicate a lot of rules in the final css ? 
For example, if we import the `_vars.sass` into 5 different sass files, wouldn't therules/vars inside the `_ vars.sass` block be repeated 5 times in the final generated css? Do this loader (or webpack) does take care of this problem somehow?

In less we could use something like `@import (reference) "less-for-reference.less";` but as I've understood this is not possible in sass, isn't it?

**Comment by alexfedoseev** [comment]
@LeonardoGentile Sass won't render any mixin / variable unless it's used to render css class or any other renderable element. So as long as you don't have any renderable element inside resources files, it will be fine. See [README#usage](https://github.com/shakacode/sass-resources-loader#usage).

**Comment by LeonardoGentile** [comment]
@alexfedoseev what do you mean by renderable elements? I guess `.my-class {}` selector would be a renderable element, isn't it?

The thing is that I've inherited a code base where there are hundreds of base classes that will never be used in the html (as "rendered" element) but extended by more specific classes sass classes. 
I guess in this case things won't work, right?

**Comment by alexfedoseev** [comment]
> what do you mean by renderable elements? I guess .my-class {} selector would be a renderable element, isn't it?

Yes, and you shouldn't put such elements in the resource file.

> The thing is that I've inherited a code base where there are hundreds of base classes that will never be used in the html (as "rendered" element) but extended by more specific sass classes.
I guess in this case things won't work, right?

Right.

```scss
/* my-resources.scss */

// good
$container-flow: row nowrap;

@mixin container() {
  display: flex;
  flex-flow: $container-flow;
}

// bad
.container {
  @include container();
}
```

**Comment by LeonardoGentile** [comment]
👍  thanks
