### ISSUE TITLE
Use loader-utils.getOptions

### ISSUE THREAD

**Issue by BenDiuguid** [shakacode/sass-resources-loader#28]
Hey, I just wanted to report this issue.

When using `sass-resources-loader` I am seeing this being logged when running webpack.

(node:68309) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
More found in this issue

I'm pretty sure this should be a simple change of updating loader-utils and changing the method from parseQuery to getOptions.

I'll try to have a PR for this soon! I just wanted to put this here first 😄

**Comment by justin808** [comment]
@BenDiuguid We're reviewing. Sorry for the delay.

**Comment by alexfedoseev** [comment]
Merged and released.
