### ISSUE TITLE
import error in sass

### ISSUE THREAD

**Issue by NaomiRison** [shakacode/sass-resources-loader#32]
I have been learning SASS for the  past 3 weeks. All of a sudden it cant find the _variables.scss file and its been in a folder called partials  since I started learning this.

Error: File to import not found or unreadable: partials/variables.

**Comment by alexfedoseev** [comment]
@NaomiRison General advice: provide a repo to reproduce your issue.

I'm guessing here, as you haven't provided a code to reproduce, but: this loader uses `fs` to resolve files w/ resources. Please make sure paths declared in your webpack config are exactly the same as in your file system: w/ extensions, no magic underscores etc.

**Comment by andrewmartin** [comment]
I just saw this, but you might want to look at our discussion here, it may help.

https://github.com/shakacode/sass-resources-loader/issues/35#issuecomment-307504385
