### ISSUE TITLE
Loader-Utils upgraded to 1.1.0 and there are issues please change package.json file

### ISSUE THREAD

**Issue by northkode** [shakacode/sass-resources-loader#37]
can you please change the package.json file to load 1.0.4 instead of ^1.0.4, loader-utils 1.1.0 is causing tons of build errors.

**Comment by justin808** [comment]
@northkode Should we update this package to support loader-utils 1.1.0?

@alexfedoseev?

**Comment by alexfedoseev** [comment]
@northkode I don't see any errors in the output. Feel free to submit PR w/ `loader-utils` bumped if you still see those.
