### ISSUE TITLE
Webpack watch launches sass-resources-loader each time

### ISSUE THREAD

**Issue by marksyzm** [shakacode/sass-resources-loader#4]
This would be absolutely perfect if it didn't rebuild the same scripts each time I altered any file within the webpack structure. So any time I change a JS file with `watch` enabled in webpack, it rebuilds my sass resources, thus vastly slowing down the build process.

**Comment by justin808** [comment]
@alexfedoseev Maybe we didn't set the cache properly for webpack, like we did for the bootstrap-loader?

**Comment by marksyzm** [comment]
Hey, it's version 0.1.0, nobody's to blame :D

**Comment by marksyzm** [comment]
Oh... it's 1.0.1 - never mind!

**Comment by justin808** [comment]
@marksyzm if you can take a look at the code...and submit a PR, that would be **great!**

Here's how I fixed this before:
https://github.com/shakacode/bootstrap-sass-loader/blob/master/bootstrap-sass-styles.loader.js#L57

addDependency tells Webpack to keep track.

```js
function addImportReturnDependency(loader, config, propertyName) {
  var fileNameResolved;
  var fileName = config[propertyName];
  if (fileName && fileName.length > 0) {
    fileNameResolved = path.relative(loader.context, fileName);

    logger.verbose(config, 'fileName for %s: %s', propertyName, fileNameResolved);
    loader.addDependency(fileNameResolved);
    return '@import \'' + fileNameResolved + '\';\n';
  }
}
```

and

https://github.com/shakacode/bootstrap-sass-loader/blob/master/bootstrap-sass-styles.loader.js#L70

```js
  this.cacheable(true);
```

CC: @alexfedoseev

**Comment by marksyzm** [comment]
Ah that makes sense... I'm never going to catch much time in the next 3
weeks though and can work around it to be fair - sorry to just dump some
crap like that but I thought you guys should know because it was pretty
major!

On Wed, 20 Jan 2016, 22:39 Justin Gordon <notifications@github.com> wrote:

> @marksyzm <https://github.com/marksyzm> if you can take a look at the
> code...and submit a PR, that would be *great!*
>
> Here's how I fixed this before:
>
> https://github.com/shakacode/bootstrap-sass-loader/blob/master/bootstrap-sass-styles.loader.js#L57
>
> addDependency tells Webpack to keep track.
>
> function addImportReturnDependency(loader, config, propertyName) {
>   var fileNameResolved;
>   var fileName = config[propertyName];
>   if (fileName && fileName.length > 0) {
>     fileNameResolved = path.relative(loader.context, fileName);
>
>     logger.verbose(config, 'fileName for %s: %s', propertyName, fileNameResolved);
>     loader.addDependency(fileNameResolved);
>     return '@import \'' + fileNameResolved + '\';\n';
>   }
> }
>
> and
>
>
> https://github.com/shakacode/bootstrap-sass-loader/blob/master/bootstrap-sass-styles.loader.js#L70
>
>   this.cacheable(true);
>
> CC: @alexfedoseev <https://github.com/alexfedoseev>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shakacode/sass-resources-loader/issues/4#issuecomment-173385115>
> .
>
-- 
Regards,
Mark Elphinstone-Hoadley
www.oxfordsourceltd.com

**Comment by alexfedoseev** [comment]
@marksyzm @justin808 I'll look into this one on the weekend.

**Comment by alexfedoseev** [comment]
@justin808 @marksyzm Those moments seem fine: [this.cacheable](https://github.com/shakacode/sass-resources-loader/blob/master/src/loader.js#L8) and [this.addDependency](https://github.com/shakacode/sass-resources-loader/blob/master/src/utils/createImport.js#L6)

I'll look further.

**Comment by alexfedoseev** [comment]
Fixed in https://github.com/shakacode/sass-resources-loader/pull/5.

**Comment by alexfedoseev** [comment]
And published to npm.
