### ISSUE TITLE
error loading scss file on windows

### ISSUE THREAD

**Issue by FreakinaBox** [shakacode/sass-resources-loader#41]
I set this lib up and have it working on my Ubuntu machine like:
```
{
                test: /\.s?css$/,
                loaders: [
                    {loader: 'style-loader', options: {sourceMap: true}},
                    {loader: 'css-loader', options: {sourceMap: true}},
                    {
                        loader: 'postcss-loader',
                        options: {
                            sourceMap: true,
                            plugins: [
                                // require('autoprefixer'),
                                // require('cssnano'),
                            ]
                        }
                    },
                    {loader: 'sass-loader', options: {sourceMap: true}},
                    {
                        loader: 'sass-resources-loader',
                        options: {
                            resources: [
                                './js/angular/pages/global.scss',
                                './node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss'
                            ]
                        },
                    },
                ]
            },
            {
                test: /\.(woff2?|ttf|eot|svg)$/,
                loader: "url-loader"
            }
```
A coworker tried running it on windows and got error
```
File to import not found or unreadable: ........node_modules♂ootstrap-sass
ssetsstylesheets♂ootstrapvariables
```

it seems very similar to the error I found here:
https://github.com/shakacode/bootstrap-sass-loader/issues/14

Is it possible that this lib needs the same update?

**Comment by coditect** [comment]
Possibly related to #40.

**Comment by justin808** [comment]
@FreakinaBox Can you please help us debug this. None of us have windows machines.

**Comment by adam-lynch** [comment]
I've the same problem. I've tried a glob like @FreakinaBox has, a glob with backslashes, and one with double-backslashes, but no luck.

**Comment by adam-lynch** [comment]
Ran into this Appveyor (you should probably use that + write tests so this kind of thing doesn't happen?) so I can't debug properly. I had a look through the code and it's not clear what's going on to me but I took out some snippets and ran them (on my Mac) with paths containing backslashes, etc. but can't see the problem. I think we're going to have to just remove sass-resources-loader for now.

**Comment by FreakinaBox** [comment]
@justin808 didn't get the notification on your mention of me till now. yes, I can help.

**Comment by bridzius** [comment]
@FreakinaBox - an identical error has been fixed in https://github.com/shakacode/sass-resources-loader/pull/42 - have you tried basing off of that PR?

**Comment by FreakinaBox** [comment]
@bridzius 
I am using `"sass-resources-loader": "shakacode/sass-resources-loader#9f65029",` inside my dependencies and now it cant find the loader

```
ERROR in ./js/angular/components/alertsFeed/alertsFeed.js
Module not found: Error: Can't resolve 'sass-resources-loader' in 'C:\www\svapp'
```

**Comment by alexfedoseev** [comment]
Try `1.3.1`. Feel free to reopen if it won't solve your issue.

**Comment by crutchcorn** [comment]
I'm still running into this error after upgrading to `1.3.1`

**Comment by justin808** [comment]
@crutchcorn can you research this? None of my team is on Windows.
