### ISSUE TITLE
error loading .sass file in .vue files with styles with scss syntax

### ISSUE THREAD

**Issue by darkylmnx** [shakacode/sass-resources-loader#44]
I have a simple Vue.js app, with .vue files that can use styles with preprocessors like sass (with scss or sass syntax)

I use the scss syntax, but my css framework, bulma css, uses sass syntax, so when i try to import one of it's sass files globally, it doesn't seem to work.

here's how i added the global file

![image](https://user-images.githubusercontent.com/1426357/28691519-8f82aa24-731d-11e7-83c5-119abb04e3b6.png)

here's the error

![image](https://user-images.githubusercontent.com/1426357/28691441-3e49bc4c-731d-11e7-8f1f-e59e22115476.png)

but when i import the sass file indepently in each files it works...
![image](https://user-images.githubusercontent.com/1426357/28691541-aea9ea70-731d-11e7-9e09-fcd4859768ff.png)

but that's what sass-resources-loader is suppose to simplify...

**Comment by justin808** [comment]
@darkylmnx None of the maintainers is using Vue. Can you please help us debug this and create either a doc or code PR to address this issue.

**Comment by justin808** [comment]
@darkylmnx feel free to request re-opening this issue.

**Comment by darkylmnx** [comment]
@justin808 well i think you misunderstood the problem here, it has no relation with Vue itself, because as i said, when i load a .sass file in vue without using your loader, it works fine, it's just cumbersome to add my sass file in each of my scss files.

But, when i try to include it globally with your loader, it doesn't work. Whereas the .scss file above works indeed.

![image](https://user-images.githubusercontent.com/1426357/28693553-82eaf980-7325-11e7-97a5-394f1f5aa765.png)

this works fine, but when i try to load a .sass file, it stops working. So this has **nothing** to do with vue.

I would like this issue to be re opened please.

**Comment by justin808** [comment]
@darkylmnx Please submit a PR with a reproduction case that we could add to our test cases:

https://github.com/shakacode/bootstrap-loader/tree/master/examples

I'll re-open again once you do that.

The issue might also be related to Windows vs. Unix

**Comment by mvilera** [comment]
@darkylmnx did you verified it's not related to the lack of indentedSyntax?

**Comment by darkylmnx** [comment]
@mvilera as explained above i'm using the Scss syntax no the Sass syntax so no indent is needed in my files, BUT, the css framework i'm using, is using Sass syntax (so indented) and why i import it using sass-ressources-loader this is the bug, whil when i'm import it directly in a scss file it works perfectly so i don't understand.

**Comment by mrmnmly** [comment]
I'm experiencing same issue here - if I'll use `scss` loader, it works fine, but I wanted to use it with `sass` :/

**Comment by Awea** [comment]
@darkylmnx @mrmnmly I get the same issue earlier and after reviewing my webpack configuration everything works fine :

**webpack.common.js**

```js
const path = require('path')

module.exports = {
  entry: [
    './src/app.js'
  ],
  output: {
    filename: 'app.js',
    path: path.resolve(__dirname, '../dist/js') 
  },
  module: {
    rules: [
      { 
        test: /\.(vue)$/, 
        loader: 'vue-loader',
        options: {
          extractCSS: process.env.NODE_ENV === 'production',
          loaders: {
            sass: [
              'vue-style-loader',
              'css-loader',
              'sass-loader?indentedSyntax',
              {
                loader: 'sass-resources-loader',
                options: {
                  resources: [
                    path.resolve(__dirname, '../sass/utilities/variables.sass')
                  ]
                }
              }
            ]
          }
        }
      },
      {
        test: /\.(js)$/,
        exclude: /(node_modules)/,
        loader: 'babel-loader',
        options: {
          presets: ['babel-preset-env']
        }
      }
    ]
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    }
  },
  node: {
    // prevent webpack from injecting useless setImmediate polyfill because Vue
    // source contains it (although only uses it if it's native).
    setImmediate: false
  }
}
```

**variables.sass**

```sass
$blue: blue
```

```vue
<template lang="pug">
  .home
    h1 Home !
</template>

<script>
  export default {
    name: 'Home'
  }
</script>

<style lang="sass">
  h1
    background: $blue
</style>
```

Hope it will helps.
