### ISSUE TITLE
Support of @imports from within SCSS files

### ISSUE THREAD

**Issue by alexfedoseev** [shakacode/sass-resources-loader#46]
I see a number of issues raised due to added support of `@import`s from within SCSS files. This is a non-recommended way of using this loader (mainly for performance reasons). We have 2 opened PRs w/ fixes (https://github.com/shakacode/sass-resources-loader/pull/42, https://github.com/shakacode/sass-resources-loader/pull/45), these will be merged as soon as they are ready. If these PRs won't solve all issues related to such `@import`s, I incline to remove this feature completely. Meanwhile, can users of this feature provide use-case(s) when this feature is required? (b/c I can't think of any)

**Comment by IAMtheIAM** [comment]
I use @import like this

Root level app.style.scss
```
@import '../../assets/styles/global';
```

```
@import "global/susy-grid-config";
@import "global/reset";
@import "global/forms";
@import "global/alignments";
@import "global/display";
@import "global/buttons";
```

I thought that is pretty standard for writing scss?

**Comment by alexfedoseev** [comment]
> I thought that is pretty standard for writing scss?

@IAMtheIAM Yep, but it causes performance issues and regressions, so I'm trying to be pragmatic here: if it's faster and safer to list these files in a webpack config, then this is the way to go.

All in all, there are few options here:
1. Things might be fixed in `1.3.1` so everyone is happy 🤞
2. Things are still broken and you can fix them **and maintain** this functionality.
3. Things are still broken and we remove this functionality, so the listing of resources must be moved to webpack config (no cons **that matter**).

P.S. Replace `global.scss` w/ `global.js` which exports an array of resolved paths to resources to keep your structure untouched (if this is your concern).

**Comment by IAMtheIAM** [comment]
@alexfedoseev  Crossing fingers for solution 1. 

Can you explain solution 3 better? For example, how does global.js feed the scss into webpack? So I export an array of resolved paths to .scss files, but then now it seems I'll need some new loader to process that file in webpack since its a .js file now. Any more tips would help so I can prepare if that needs to happen. Thanks

**Comment by alexfedoseev** [comment]
> Can you explain solution 3 better? For example, how does global.js feed the scss into webpack? So I export an array of resolved paths to .scss files, but then now it seems I'll need some new loader to process that file in webpack since its a .js file now. Any more tips would help so I can prepare if that needs to happen. Thanks

@IAMtheIAM For example, there's SCSS file w/ resources index at path `path/to/resources/index.scss`:

```scss
@import "./colors";
@import "./sizes";
...
```

In webpack config loader is defined like this:

```js
{
  loader: 'sass-resources-loader',
  options: {
    resources: './path/to/resources/index.scss',
  }
}
```

Instead of using SCSS imports you can do the following:

`path/to/resources/index.js`

```js
import path from 'path';

const resources = [
  'colors.scss',
  'sizes.scss',
  ...
];

export default resources.map(file => path.resolve(__dirname, file));
```

`webpack.config.js`

```js
import sassResources from './path/to/resources';
 ...

{
  loader: 'sass-resources-loader',
  options: {
    resources: sassResources,
}
```

**Comment by IAMtheIAM** [comment]
I see, thanks, that does make sense. I would still put that at last resort, because it loses the ability to use "navigate to code" in the IDE and quickly switch to the scss file. But if this is the only way, then it will do.

**Comment by IAMtheIAM** [comment]
Good news for all. Version 1.3.1 fixed the issue! My @import statements now are resolve with no problem. Thanks for fixing this @alexfedoseev! This issue can be closed.
