### ISSUE TITLE
Webpack 3 compatibility?

### ISSUE THREAD

**Issue by nemad** [shakacode/sass-resources-loader#49]
Is this compatible with webpack 3? I'm getting a strange issue since I updated:

> ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./node_modules/sass-resources-loader/lib/loader.js?{"resources":["./node_modules/bootstrap/scss/_variables.scss","./node_modules/bootstrap/scss/mixins/*.scss"]}!./ClientApp/app/app.component.scss
> Module build failed: 
> undefined
>                        ^
>       Argument `$color` of `darken($color, $amount)` must be a color

Any idea what can cause this? Config is the same as in the guide, and worked fine until now.

**Comment by justin808** [comment]
@alexfedoseev Are we using the sass-resources-loader with Webpack v3 in https://www.friendsandguests.com?

**Comment by alexfedoseev** [comment]
@justin808 Yes, we do.

I'm not sure if this issue is related to Webapck 3. @nemad Can you provide a repo to reproduce? Without it, I can't say why `$color` is `undefined`.

Closing this for now, feel free to reopen w/ the link to a repo.

**Comment by nemad** [comment]
Okay, so actually it was a problem with the bootstrap beta 4, I had to include some other scss file before the other. (there wasnt any info about this when I wrote this issue back then.) Just leave this here, might help someone.

**Comment by idknox** [comment]
@alexfedoseev Any chance you could explain how to use this with Webpacker 3?

**Comment by alexfedoseev** [comment]
@idknox Sorry, I have zero Webpacker 3 experience. Try to open separate issue and describe problems you run into. Somebody might help you out.

**Comment by drw89** [comment]
are there any plan to merge the following branch ( https://github.com/GeReV/sass-resources-loader/commit/b4284e019dfb4417338e323d713f82d68528f828)??

**Comment by alexfedoseev** [comment]
@drw89 Merged and released `1.3.2`.
