### ISSUE TITLE
Include node_modules sass files?

### ISSUE THREAD

**Issue by milewski** [shakacode/sass-resources-loader#51]
Hello i cant get node_modules included this way.

```js
{
    loader: 'sass-resources-loader',
    options: {
        resources: [
            '~csstyle/csstyle',
            path.resolve(__dirname, '../source/assets/sass/**/*.global.scss')
        ]
    }
},
```

i end up creating a `mixing.scss` file importing`'~csstyle/csstyle` inside to make it work.. but as advised in the README.. do not @import stuff inside your resources file.... or you will get low performance.... 

is there any solution to this?

**Comment by alexfedoseev** [comment]
@milewski Nope, you can't, b/c it's not in SCSS scope so you can't use SCSS syntax. These paths are used by `fs`: it reads content of a file and loader inlines it, so just provide an absolute path to your resources files.

**Comment by milewski** [comment]
"that could be a easy feature to add" detect the existence of ~ and replace with the path of node_modules.. i might do a PR later
