### ISSUE TITLE
Source map line number

### ISSUE THREAD

**Issue by planetflash** [shakacode/sass-resources-loader#62]

**Comment by planetflash** [comment]
If anyone has the same issue, it seemed to be due to me having SourceMaps:true set in postCSS options, which is not needed

**Comment by betorobson** [comment]
I found a solution, in `sass-loader` you must add option 'outputStyle: 'compressed'.

Example
```javascript
{
	loader: 'sass-loader',
	options: {
		sourceMap: true,
		outputStyle: 'compressed',
	}
},

```
