### ISSUE TITLE
question with use @import in index.scss

### ISSUE THREAD

**Issue by vinceok** [shakacode/sass-resources-loader#63]
in my project（a vue.js & webpack project）, i used package:**sass-resources-loader**,then i found:

i use index.scss as a entry scss file, and import other scss file in index, the project is run ok，but when i review the source code, i find some repeating style in html>head, is there have any solution?

```
scss: generateLoaders('sass').concat(
      {
        loader: 'sass-resources-loader',
        options: {
          resources: path.resolve(__dirname, '../src/assets/styles/index.scss')
        }
      }
    ),
```

```
@import 'normalize.scss';
@import 'reset.scss';
@import 'vars.scss';
@import 'mixins.scss';
@import 'utils.scss';
@import 'icon.scss';
```

**Comment by alexfedoseev** [comment]
Easy:
1. Read docs: https://github.com/shakacode/sass-resources-loader#usage
2. Remove everything that's renderable from `index.scss` (e.g. `normalize.scss`, `reset.scss` etc).
