### ISSUE TITLE
How can we add this to a Vue webpack template?

### ISSUE THREAD

**Issue by trusktr** [shakacode/sass-resources-loader#67]
For example, here's the webpack config: https://github.com/vuejs-templates/webpack/blob/develop/template/build/webpack.base.conf.js

**Comment by RomainFrancony** [comment]
CSS loaders are generated in ```build/utils.js```, go to line 36 of this file, you will see a condition 
```
if (loader) {
  loader.push(...)
}
``` 
Add this inside the if condition


```
if(loader === 'sass'){
  loaders.push({
  loader: 'sass-resources-loader',
  options: {
    resources: 'path/to/your/file.scss'),
    },
  })
}
```

I don't know if it's the best way to do it but it work.

**Comment by justin808** [comment]
@RomainFrancony If you'd like to make a doc PR, that would be amazing.

**Comment by justin808** [comment]
And thanks @RomainFrancony for the help!

**Comment by RomainFrancony** [comment]
@justin808 I will do the PR this evening
