### ISSUE TITLE
Sass loader fails 

### ISSUE THREAD

**Issue by veeramarni** [shakacode/sass-resources-loader#7]
Getting following error when using sass-resource-loader from [metric-webpack](https://github.com/thereactivestack/meteor-webpack/blob/master/packages/sass/webpack.config.js) project. 

```
ERROR in ./~/css-loader?{"localIdentName":"[name]__[local]__[hash:base64:5]"}!./~/sass-loader!./~/sass-resources-loader/lib/loader.js?{}!./~/style-loader!./~/css-loader?{"localIdentName":"[name]__[local]__[hash:base64:5]"}!./~/sass-loader?{}!./~/sass-resources-loader/lib/loader.js!./~/reactionic/dist/scss/ionic-scss/_bar.scss
Module build failed: 
undefined
^
      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "content = requi..."
      in /app/node_modules/reactionic/dist/scss/ionic-scss/_bar.scss (line 1402, column 2)
 @ ./~/reactionic/dist/scss/ionic-scss/_bar.scss 4:14-434 13:2-17:4 14:20-440

```

Here is how i have configured.
In jsx file i have imported
`import 'reactionic/dist/scss/ionic-scss/_bar.scss';`

In webpack.json, i have added following. 

```
{
  "sassResources": ["./node_modules/reactionic/dist/scss/ionic-scss/_variables.scss","./node_modules/reactionic/dist/scss/ionic-scss/_mixins.scss"]
}
```

**Comment by alexfedoseev** [comment]
@veeramarni Can you push repo to reproduce this issue?

**Comment by nic004** [comment]
I had same issue.
 
In my case,

// one line comment 
$font-size: 36px;
=> pass

$font-size: 36px;  // comment at end of line
=> fail

**Comment by justin808** [comment]
@veeramarni @nic004 If you can give @alexfedoseev and I a simple repro case, we can probably fix the issue.

**Comment by tapesec** [comment]
any news about this issue ?

**Comment by justin808** [comment]
We need a simple repro case.

**Comment by justin808** [comment]
@nic004 does simply not having comments on the same lines fix the issues?
