### ISSUE TITLE
Vue - Global resources throws error

### ISSUE THREAD

**Issue by AshwinTayson** [shakacode/sass-resources-loader#74]
Hello I have added the config to the utils.js as mentioned but it throws error for all the vue files which contains style tag with lang="sass"

Here is the directory structure
build
--utils.js
src
--assets
----sass
------index.sass
------all other sass files

index.sass
```
@import './bootstrap-helper'
@import './variables'
@import './override'
@import './global'
```

App.vue
<template>
  <div id="app">
    <router-view class="body"/>
  </div>
</template>

<script>
export default {
  name: 'App',
};
</script>

<style lang="sass">
</style>

this throws error

> error  in ./src/App.vue
> 
> Module build failed: Error:
>       Something wrong with provided resources.
>       Make sure 'options.resources' is String or Array of Strings.
> 
>     at Object.module.exports (/home/impact/Projects/belk-promosmart/node_modules/sass-resources-loader/lib/loader.js:73:18)
> 
>  @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7ba5bd90","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"indentedSyntax":true,"sourceMap":true}!./node_modules/sass-resources-loader/lib/loader.js?{"resources":"./src/assets/sass/index.sass"}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-484 13:3-17:5 14:22-492
>  @ ./src/App.vue
>  @ ./src/main.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

At line 43 of utils.js I have

```
  if (loader === 'sass') {
    loaders.push({
      loader: 'sass-resources-loader',
      options: {
        resources: './src/assets/sass/index.sass',
      },
    });
  }
```

Do I need to change webpack.base.conf.js also?

**Comment by RomainFrancony** [comment]
Try giving the full path of the file in the config: 
```path.resolve(__dirname, "../src/assets/sass/index.sass"),```

**Comment by justin808** [comment]
@AshwinTayson please open again if this did not fix your issue ^^^.
