### ISSUE TITLE
Can't find sass resources ERROR with 1.3.4

### ISSUE THREAD

**Issue by jvarho** [shakacode/sass-resources-loader#79]
Since updating from 1.3.3 to 1.3.4 I get an error like this:

        ERROR in ./~/css-loader?modules&sourceMap&localIdentName=[name]__[local]___[hash:base64:5]!./~/sass-loader!./~/sass-resources-loader/lib/loader.js!./~/import-glob-loader!./src/components/BaseComponent.scss
        Module build failed: Error: Can't find sass resources in your
    config. Make sure loader.options.resources exists
            at Object.module.exports
    (./node_modules/sass-resources-loader/lib/loader.js:53:17)

I can confirm that downgrading to 1.3.3 fixes the issue.

Looks like this may be caused by #66 – if that is intended, you should consider releasing 1.3.5 that reverts it and only dropping support in a future 1.4 or 2.0. It isn't very nice to break things in what is supposed to be a backwards compatible release if you follow semver: https://docs.npmjs.com/getting-started/semantic-versioning

**Comment by derwaldgeist** [comment]
Same problem here. Broke our production build on a CI machine that wasn't using `package-lock.json`. Introducing breaking changes in a sub-minor is not a good idea :-)

**Comment by justin808** [comment]
@jvarho @derwaldgeist can you confirm that you're both on Webpack v1? And the fix for #66 just removed support for Webpack v1?

**Comment by jvarho** [comment]
Yes, at least my project is on webpack v1.15.

**Comment by derwaldgeist** [comment]
Yes, I am using webpack 1.14.0 in this project.

**Comment by justin808** [comment]
@david-ogalego @alexfedoseev 

I'd agree with:

> Looks like this may be caused by #66 – if that is intended, you should consider releasing 1.3.5 that reverts it and only dropping support in a future 1.4 or 2.0. It isn't very nice to break things in what is supposed to be a backwards compatible release if you follow semver: https://docs.npmjs.com/getting-started/semantic-versioning

Should I push a v2 that removes Webpack v1 support?

**Comment by derwaldgeist** [comment]
It‘s pretty unusual to drop support for something in a sub-minor release. I would also recommend to do this in a 2.x

**Comment by derwaldgeist** [comment]
How can I confirm this?

**Comment by jvarho** [comment]
I don't have a setup where I could test a non-pakaged version easily, sorry.

**Comment by justin808** [comment]
OK. See the https://github.com/shakacode/sass-resources-loader/blob/master/CHANGELOG.md

and please try out 1.3.5 and 2.0.0.

Thanks,

Justin

**Comment by jvarho** [comment]
Confirmed. 1.3.5 fixes the issue for me.
