### ISSUE TITLE
Problem to import SCSS files in SASS files.

### ISSUE THREAD

**Issue by whitetrefoil** [shakacode/sass-resources-loader#8]
According to the error log, it seems the SCSS file was parsed as a SASS file when it was imported in a SASS file.

When manually `@import` that SCSS file it works fine.

**webpack.conf.js:**
```javascript
// ......

module: {
  loaders: [
    {
      test   : /\.sass$/,
      loaders: ['style', 'css', 'sass', 'sass-resources'],
    },
    {
      test   : /\.scss$/,
      loaders: ['style', 'css', 'sass?config=scssLoader', 'sass-resources'],
    },
  ],
},

// ......

sassLoader: {
  indentedSyntax: true,
  precision     : 8,
},
scssLoader: {
  indentedSyntax: false,
  precision     : 8,
},
sassResources: [
  path.resolve(__dirname, 'src/css/_variables.scss'),
],

// ......
```
**src/css/_variables.scss:**
```scss
@charset "UTF-8";

@mixin test-mixin {
  color: red;
}
```

**src/css/app.sass:**
```sass
@charset "UTF-8"

body
  +test-mixin
```

**error log:**
```
ERROR in ./~/css-loader!./~/sass-loader!./~/sass-resources-loader/lib/loader.js!./src/css/test.sass
Module build failed: 

             ^
      Invalid CSS after "@mixin test-mixin() {": expected "}", was "{"
      in ....../src/css/test.sass (line 3, column 22)
 @ ./src/css/test.sass 4:14-178 13:2-17:4 14:20-184
```

**Comment by justin808** [comment]
@whitetrefoil Could you stick to scss?

otherwise, can you help us debug this and submit a PR?

**Comment by whitetrefoil** [comment]
I chose not to disturb the legacy code in my project for now.  I'll see if there's anything I can do here after it's finished.

**Comment by alexfedoseev** [comment]
@whitetrefoil It won't work, b/c content of the resource files is inlined. Reason: performance issue. Please take a look at my comment in https://github.com/shakacode/sass-resources-loader/issues/6.

I'm closing this, b/c it's kinda dup of #6. Let's continue there.
