### ISSUE TITLE
How to Properly Import Google Fonts

### ISSUE THREAD

**Issue by mxdavis** [shakacode/sass-resources-loader#80]
What would be the best way to import google fonts into sass without using `@import url('https://fonts.googleapis.com/...);` which breaks the build.

```
WARNING in ./node_modules/css-loader??ref--1-2!./node_modules/postcss-loader/lib??ref--1-3!./node_modules/sass-loader/lib/loader.js!./node_modules/sass-resources-loader/lib/loader.js??ref--1-5!./app/javascript/packs/shared/styles/base.scss
(Emitted value instead of an instance of Error) postcss-smart-import: /app/javascript/packs/shared/styles/base.scss:2:1: Failed to find 'https:/fonts.googleapis.com/css?family=Lora:300,400,400i,700'
    in [ 
        /home/circleci/donaldson/app/javascript/packs/shared/styles
    ]
 @ ./app/javascript/packs/shared/styles/base.scss 2:14-290
```

Thanks!

**Comment by mxdavis** [comment]
I did it with https://github.com/typekit/webfontloader

**Comment by mihailthebuilder** [comment]
`@import url('https://fonts.googleapis.com/...')` works now when you add it to any scss file **except** those  in the **options.resources** array. Check out **src/index.scss** and **webpack.config.js** in my repo: https://github.com/mihailthebuilder/tech-asia
