### ISSUE TITLE
react  webpack4    

### ISSUE THREAD

**Issue by laiwoyaojubaoni** [shakacode/sass-resources-loader#83]
The previous react project first installed sass-resources-loader without reference to any configuration in webpack.config.js to reference global variables. However, after deleting the plugin and reinstalling it, it always reports an error. Whether it is based on the configuration above github or google is wrong. The newly created react project has been reporting an error（以前的 react 项目第一次安装 sass-resources-loader 的时候没有配置 webpack.config.js里面的任何配置就可以引用全局变量。然而误删该插件重新安装后则一直报错。不管是根据 github 上面的配置还是 google 都报错。最新创建的 react 项目则一直报错）

![image](https://user-images.githubusercontent.com/37793236/51231118-59e12d00-199d-11e9-9c4f-ca886d1f6704.png)
![image](https://user-images.githubusercontent.com/37793236/51231332-13400280-199e-11e9-9ae7-1752480ef8f5.png)
![image](https://user-images.githubusercontent.com/37793236/51231345-2652d280-199e-11e9-8b9c-b790a5b896fa.png)

**Comment by justin808** [comment]
This is not enough info. Your error says you have an undefined variable.

**Comment by laiwoyaojubaoni** [comment]
I know that no variables are found, local variables can be found, but now there is a global variable in index.scss. How can I configure to find global variables?
