### ISSUE TITLE
Webpack 4 config

### ISSUE THREAD

**Issue by barth12** [shakacode/sass-resources-loader#84]
Hi guys, 
Could anyone share the config for webpack4 in react environment (I've just used react-create-app v2 with webpack 4). 
For some reason I'm getting: 

```
./src/components/Registration/_registration.scss (./node_modules/css-loader??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/components/Registration/_registration.scss)
  color: $testColor;
        ^
      Undefined variable: "$testColor".
      in /Users/Bartosz/Projects/penzo-web/src/components/Registration/_registration.scss (line 2, column 10)
```

My config is just copied from webpack 2 site example: 

```   
 {
      test: /\.scss$/,
      use: [
        'style-loader',
        'css-loader',
        'postcss-loader',
        'sass-loader',
        {
          loader: 'sass-resources-loader',
          options: {
            // Provide path to the file with resources
            resources: './path/to/resources.scss',
          },
        },
      ],
    },
```

Any help much appropriated.

**Comment by justin808** [comment]
@barth12 If you can update this to Webpack v4: https://github.com/shakacode/sass-resources-loader/blob/master/example/package.json, my team will review.

**Comment by ehsanakbarzadeht** [comment]
i have same issue in react and webpack config

**Comment by Xandromus** [comment]
I'm running into the same issue

**Comment by justin808** [comment]
I'm pretty sure this is just a configuration issue. Check the examples.

It's updated to webpack 4.44.1.

https://github.com/shakacode/sass-resources-loader/blob/master/example/package.json#L60
