### ISSUE TITLE
Havin

### ISSUE THREAD

**Issue by RavaliPothepalli** [shakacode/sass-resources-loader#86]

**Comment by justin808** [comment]
Pay attention to the path shown in the error message.

Any ideas from that?

**Comment by Judahmeek** [comment]
You mean the mention of `liftkit.scss`?

**Comment by Judahmeek** [comment]
@RavaliPothepalli does `node_modules@crown\liftkit-style\assets\scss\liftkit.scss` looks weird. Any idea what `node_modules@crown` means?
